_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
n_episodes:
    value: 15000
n_eval_episodes:
    value: 10
n_trials:
    value: 50
